version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis
    entrypoint: ["sh", "-c", "until nc -z db 3306; do echo waiting for mysql; sleep 2; done; docker-php-entrypoint php-fpm"]

  # MySQL container
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: dating_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Redis container
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
